window.onload = function()
{
    if(screen.width >= 1200)
   {
        ScrollReveal().reveal('#git', {delay: 500, reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#js', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#educit', {delay: 700,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#php', {delay: 800,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#sql', {delay: 900,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#dighou', {delay: 1000,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#java', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.micro', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.promo', {delay: 700,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.uvc', {delay: 800,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.aco', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.ymm', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.intraandes', {delay: 700,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.electroven', {delay: 800,reset:true,distance: '5%',origin: 'top'})
   } else if(screen.width >= 992 && screen.width <1200)
   {
        ScrollReveal().reveal('#git', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#js', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#educit', {delay: 700,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#php', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#sql', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#dighou', {delay: 700,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#java', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.micro', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.promo', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.uvc', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.aco', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.ymm', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.intraandes', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.electroven', {delay: 700,reset:true,distance: '5%',origin: 'top'})
   
   } else if (screen.width >= 768 && screen.width <992)
   {
        ScrollReveal().reveal('#html', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#css', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#git', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#js', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#php', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#sql', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#java', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#utn', {delay: 500,reset:true,distance: '5%',origin: 'top'}) 
        ScrollReveal().reveal('#educit', {delay: 600,reset:true,distance: '5%',origin: 'top'})     
        ScrollReveal().reveal('#dighou', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.micro', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.promo', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.uvc', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.aco', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.ymm', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.intraandes', {delay: 600,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.electroven', {delay: 500,reset:true,distance: '5%',origin: 'top'})
   } else
   {
        ScrollReveal().reveal('#html', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#css', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#git', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#js', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#php', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#sql', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#java', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('#utn', {delay: 500,reset:true,distance: '5%',origin: 'top'}) 
        ScrollReveal().reveal('#educit', {delay: 500,reset:true,distance: '5%',origin: 'top'})     
        ScrollReveal().reveal('#dighou', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.micro', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.promo', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.uvc', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.aco', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.ymm', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.intraandes', {delay: 500,reset:true,distance: '5%',origin: 'top'})
        ScrollReveal().reveal('.electroven', {delay: 500,reset:true,distance: '5%',origin: 'top'})
   }
}