window.onload = function()
{
    if(screen.width >= 1200)
   {
        ScrollReveal().reveal('#git', {delay: 500})
        ScrollReveal().reveal('#js', {delay: 600})
        ScrollReveal().reveal('#educit', {delay: 700})
        ScrollReveal().reveal('#php', {delay: 800})
        ScrollReveal().reveal('#sql', {delay: 900})
        ScrollReveal().reveal('#dighou', {delay: 1000})
        ScrollReveal().reveal('#java', {delay: 500})
        ScrollReveal().reveal('.micro', {delay: 600})
        ScrollReveal().reveal('.promo', {delay: 700})
        ScrollReveal().reveal('.uvc', {delay: 800})
        ScrollReveal().reveal('.aco', {delay: 500})
        ScrollReveal().reveal('.ymm', {delay: 600})
   } else if(screen.width >= 992 && screen.width <1200)
   {
        ScrollReveal().reveal('#git', {delay: 500})
        ScrollReveal().reveal('#js', {delay: 600})
        ScrollReveal().reveal('#educit', {delay: 700})
        ScrollReveal().reveal('#php', {delay: 500})
        ScrollReveal().reveal('#sql', {delay: 600})
        ScrollReveal().reveal('#dighou', {delay: 700})
        ScrollReveal().reveal('#java', {delay: 500})
        ScrollReveal().reveal('.micro', {delay: 500})
        ScrollReveal().reveal('.promo', {delay: 600})
        ScrollReveal().reveal('.uvc', {delay: 500})
        ScrollReveal().reveal('.aco', {delay: 600})
        ScrollReveal().reveal('.ymm', {delay: 500})
   
   } else if (screen.width >= 768 && screen.width <992)
   {
        ScrollReveal().reveal('#html', {delay: 500})
        ScrollReveal().reveal('#css', {delay: 600})
        ScrollReveal().reveal('#git', {delay: 500})
        ScrollReveal().reveal('#js', {delay: 600})
        ScrollReveal().reveal('#php', {delay: 500})
        ScrollReveal().reveal('#sql', {delay: 600})
        ScrollReveal().reveal('#java', {delay: 500})
        ScrollReveal().reveal('#utn', {delay: 500}) 
        ScrollReveal().reveal('#educit', {delay: 600})     
        ScrollReveal().reveal('#dighou', {delay: 500})
        ScrollReveal().reveal('.micro', {delay: 500})
        ScrollReveal().reveal('.promo', {delay: 600})
        ScrollReveal().reveal('.uvc', {delay: 500})
        ScrollReveal().reveal('.aco', {delay: 600})
        ScrollReveal().reveal('.ymm', {delay: 500})
   } else
   {
        ScrollReveal().reveal('#html', {delay: 500})
        ScrollReveal().reveal('#css', {delay: 500})
        ScrollReveal().reveal('#git', {delay: 500})
        ScrollReveal().reveal('#js', {delay: 500})
        ScrollReveal().reveal('#php', {delay: 500})
        ScrollReveal().reveal('#sql', {delay: 500})
        ScrollReveal().reveal('#java', {delay: 500})
        ScrollReveal().reveal('#utn', {delay: 500}) 
        ScrollReveal().reveal('#educit', {delay: 500})     
        ScrollReveal().reveal('#dighou', {delay: 500})
        ScrollReveal().reveal('.micro', {delay: 500})
        ScrollReveal().reveal('.promo', {delay: 500})
        ScrollReveal().reveal('.uvc', {delay: 500})
        ScrollReveal().reveal('.aco', {delay: 500})
        ScrollReveal().reveal('.ymm', {delay: 500})
   }
}